apiVersion: v1
data:
  config.yaml: |
    configManager:
      source: OCM
      ocmBaseUrl: https://api.stage.openshift.com
      watchInterval: 60
    maintenance:
      controlPlaneTime: 130
      ignoredAlerts:
        controlPlaneCriticals:
        # ClusterOperatorDown - https://bugzilla.redhat.com/show_bug.cgi?id=1955300
        - ClusterOperatorDown
    scale:
      timeOut: 30
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
      - PruningCronjobErrorSRE
      - PrometheusRuleFailures
      - CannotRetrieveUpdates
      - FluentdNodeDown
      # https://bugzilla.redhat.com/show_bug.cgi?id=1986981
      - PrometheusRemoteWriteBehind
      - KubePersistentVolumeErrors
      - PrometheusBadConfig
      - PrometheusRemoteStorageFailures
      - AlertmanagerMembersInconsistent
      - AlertmanagerClusterFailedToSendAlerts
      - AlertmanagerConfigInconsistent
      - AlertmanagerClusterDown
      - KubeStateMetricsListErrors
      - KubeStateMetricsWatchErrors
      - ThanosRuleSenderIsFailingAlerts
      - ThanosRuleHighRuleEvaluationFailures
      - ThanosNoRuleEvaluations
      ignoredNamespaces:
      - openshift-logging
      - openshift-redhat-marketplace
      - openshift-operators
      - openshift-customer-monitoring
      - openshift-cnv
      - openshift-route-monitoring-operator
      - openshift-user-workload-monitoring
      - openshift-pipelines
    extDependencyAvailabilityChecks:
      http:
        timeout: 10
        urls:
          - https://api.stage.openshift.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"configManager:\n  source: OCM\n  ocmBaseUrl: https://api.stage.openshift.com\n  watchInterval: 60\nmaintenance:\n  controlPlaneTime: 130\n  ignoredAlerts:\n    controlPlaneCriticals:\n    # ClusterOperatorDown - https://bugzilla.redhat.com/show_bug.cgi?id=1955300\n    - ClusterOperatorDown\nscale:\n  timeOut: 30\nupgradeWindow:\n  delayTrigger: 30\n  timeOut: 120\nnodeDrain:\n  timeOut: 45\n  expectedNodeDrainTime: 8\nhealthCheck:\n  ignoredCriticals:\n  - DNSErrors05MinSRE\n  - MetricsClientSendFailingSRE\n  - UpgradeNodeScalingFailedSRE\n  - UpgradeClusterCheckFailedSRE\n  - PruningCronjobErrorSRE\n  - PrometheusRuleFailures\n  - CannotRetrieveUpdates\n  - FluentdNodeDown\n  # https://bugzilla.redhat.com/show_bug.cgi?id=1986981\n  - PrometheusRemoteWriteBehind\n  - KubePersistentVolumeErrors\n  - PrometheusBadConfig\n  - PrometheusRemoteStorageFailures\n  - AlertmanagerMembersInconsistent\n  - AlertmanagerClusterFailedToSendAlerts\n  - AlertmanagerConfigInconsistent\n  - AlertmanagerClusterDown\n  - KubeStateMetricsListErrors\n  - KubeStateMetricsWatchErrors\n  - ThanosRuleSenderIsFailingAlerts\n  - ThanosRuleHighRuleEvaluationFailures\n  - ThanosNoRuleEvaluations\n  ignoredNamespaces:\n  - openshift-logging\n  - openshift-redhat-marketplace\n  - openshift-operators\n  - openshift-customer-monitoring\n  - openshift-cnv\n  - openshift-route-monitoring-operator\n  - openshift-user-workload-monitoring\n  - openshift-pipelines\nextDependencyAvailabilityChecks:\n  http:\n    timeout: 10\n    urls:\n      - https://api.stage.openshift.com\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"hive.openshift.io/managed":"true"},"name":"managed-upgrade-operator-config","namespace":"openshift-managed-upgrade-operator"}}
  creationTimestamp: "2022-03-22T12:39:51Z"
  labels:
    hive.openshift.io/managed: "true"
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
  resourceVersion: "24959"
  uid: a1ab5b25-dc7a-4cc8-b88e-efb3f9836c61
